
site_name: Your Project
site_url: https://vfedotovs.github.io/test_makefile
site_author: Valentins Fedotovs



# Navigation
nav:
    - Home: index.md
    - Getting Started: getting-started.md
    - User Guide:
        - Overview: user-guide/index.md
        - Installation: user-guide/installation.md
