
site_name: Test_makefile
site_url: https://vfedotovs.github.io/test_makefile
site_author: Valentins Fedotovs


# Navigation
nav:
    - Home: index.md
    - Tutorials: tutorials.md
    - How To Guides: how-to-guides.md
    - References: reference.md
    - Explanations: explanation.md
